[package]
name = "reqwest_multi5_crossbeam_scope"
version = "0.1.0"
authors = ["Lenovo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest="0.9.20"
crossbeam="0.7.2"